### ISSUE TITLE
Filling multiple WI fields

### ISSUE THREAD

**Issue by nitramsk** [AdhocAdam/smletsexchangeconnector#129]
Would it be possible to parse email and based on some Key words, fill workitems? For example system like Jira will send structured email and exchange connector will based on that fill Change request.

Structure email can looks like:

[Title]: Jira Case
[Description]: Text for filing description field
[Reason]: Again some text
etc..
 
Or maybe it is possible to do this through CustomEvents powershell?

I am still quite new with SMLets exchange connector...

M,

**Comment by AdhocAdam** [comment]
This certainly sounds possible, but going strictly on the example above it's going to be a bit of a challenge. The core processing logic is going to be looking for SCSM Prefixes in the email subject to trigger Update-WorkItem and when it doesn't find a Prefix it triggers a New-WorkItem. Just like the stock connector before it an Update generally appends to the Action Log and a New Work Item the Subject becomes Title and Body becomes Description.

**But** the way around this that comes to mind and one I've suggested for others, is if you can get the originating system (in this case Jira) to include some unique prefix in the subject (e.g. JIRA###) then you could introduce a custom regex match scenario on the core processing. From here you could then insert you own wholly custom logic. This customization extends itself not just to Jira, but really any external ticketing system.

Check out the following section in the processing loop - https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L3137-L3159

This customization is also one I highlighted in a recent blogpost here on the repo seen here https://adhocadam.github.io/smletsexchangeconnector/Preserving-Customizations-through-Upgrades/. In this case, I've gone a step further with suggesting a class extension and runbook on Work Items so that external ticketing system can update, in addition to create Work Items within SCSM.

**Comment by AdhocAdam** [comment]
Just checking in @nitramsk - any progress?

**Comment by nitramsk** [comment]
Sorry for long reply. I was playing with it just a little bit, but currently for testing I prepared this
```
#Code added in Invoke-AfterCreateCR
$KeywordsReason = "Reason: "
$KeywordsEndReason = "/Reason"
$KeywordsScheduledStartDate = "ScheduledStartDate: "
$KeywordsEndScheduledStartDate = "/ScheduledStartDate"
$KeywordsScheduledEndDate = "ScheduledEndDate: "
$KeywordsEndScheduledEndDate = "/ScheduledEndDate"   
                    
#Regex pattern to compare two strings
                 
$PatternReason = "$KeywordsReason(.*?)$KeywordsEndReason"
$PatternScheduledStartDate = "$KeywordsScheduledStartDate(.*?)$KeywordsEndScheduledStartDate"
$PatternScheduledEndDate = "$KeywordsScheduledEndDate(.*?)$KeywordsEndScheduledEndDate"

#Perform the opperation
$ResultReason = [regex]::Match($description,$PatternReason).Groups[1].Value
$ResultScheduledStartDate = [regex]::Match($description,$PatternScheduledStartDate).Groups[1].Value
$ResultScheduledEndDate = [regex]::Match($description,$PatternScheduledEndDate).Groups[1].Value
Set-SCSMObject -SMObject $newWorkItem -PropertyHashtable @{"Reason" = $ResultReason; "ScheduledStartDate" = $ResultScheduledStartDate; "ScheduledEndDate" = $ResultScheduledEndDate} @scsmMGMTParams"
```

It is not perfect and need lot of tweaks. I was thinking about adding mapping of SCSM fields and Keywords to some additional file, but not had time for now.

**Comment by AdhocAdam** [comment]
I must admit I had never even considered the regex approach to parsing out the email into the CR. So to say the least - 10 points for creativity @nitramsk! 😄

**Comment by AdhocAdam** [comment]
Just doing some housekeeping and will be closing this out.

If you have any more questions, let me know and thanks for using the connector!
