### ISSUE TITLE
Add  Date To Email Attachment Filename

### ISSUE THREAD

**Issue by infiniterecursion** [AdhocAdam/smletsexchangeconnector#136]
I've noticed in the stock exchange connector that each subsequent email after the first has a time stamp appended to the attached filename in an incident. Currently, this connector attaches every email with "message.eml" as the filename, even when multiple files are attached. Would it be possible to have this connector mimic the stock connector behavior?

**Comment by AdhocAdam** [comment]
The reason I originally passed on this was because it felt redundant given there was already an Attached Date property. Granted, these are two wholly separate functions (Attach-EmailToWorkItem and Attach-FileToWorkItem) in the connector so technically there isn't a reason this can't happen. But I have to ask - is there a specific reason this does not suffice?

https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L1542-L1549

**Comment by infiniterecursion** [comment]
The stock views in the Cireson portal do not expose the Attached Date information and our Tier 1 analysts were complaining that they had to click through several to find the most recent one.

**Comment by infiniterecursion** [comment]
I did try modifying the script in our dev environment to include the date in the filename, but had a bit of trouble with getting the date function to return something that was formatted properly and in the right data type to append to the filename string.

**Comment by AdhocAdam** [comment]
> The stock views in the Cireson portal do not expose the Attached Date information and our Tier 1 analysts were complaining that they had to click through several to find the most recent one.

I had a feeling you might say that. In which case, I have a way to solve this at a slightly different level. Head into:

..\inetpub\CiresonPortal\Scripts\forms\predefined\fileAttachmentsDragDrop\view.html

This is the file that controls the layout for the File Attachments and how they get rendered on the Related Items tab. On line 28 of this you should see:

```javascript
<span>#: DisplayName #</span>
```

Immediately after this line add the following:
```javascript
<span>#: new Date(AddedDate).toLocaleString() #</span>
```

So then Line 28 is still the DisplayName, but line 29 is now the AddedDate property

```javascript
<span>#: DisplayName #</span>
<span>#: new Date(AddedDate).toLocaleString() #</span>
```

Keep in mind, since this is an edit of a stock control every upgrade you'd have to reset this. Otherwise, all of your file attachments have dates now!

**Comment by AdhocAdam** [comment]
Hey there @infiniterecursion - just wanted to check back in and see if this was a viable alternative? Also worth mentioning that Jeff has raised his own version as well in the community over [here](https://community.cireson.com/discussion/5008/file-attachment-date-and-time).

**Comment by infiniterecursion** [comment]
Sorry Adam, got busy with another project so haven't had time to try this yet, but it sounds like a possible solution. I wasn't aware the database tracked the added date for email attachments, so that is good to hear. I'll see if I can try your solution this week and report back my findings.

**Comment by AdhocAdam** [comment]
No worries whatsoever. Look forward to hearing back!

**Comment by infiniterecursion** [comment]
Adam,
Thanks! I tried your solution and my techs are now happy. I'll give Jeff's solution a try in the near future as that looks like it can be included in CustomSpace and be able to survive upgrades. I appreciate all your help!

**Comment by AdhocAdam** [comment]
Most excellent to hear.
