### ISSUE TITLE
Issue with Multiple Inbox and Distribution Groups

### ISSUE THREAD

**Issue by infiniterecursion** [AdhocAdam/smletsexchangeconnector#141]
**Describe the bug**
I'm noticing an issue with the multiple inboxes feature where the service manager inbox is part of a global distribution group. When the connector encounters the message it will create an incident but not apply the appropriate template nor mark the message as read or move it to deleted items. It then reprocesses the message the next time the scheduled task is run leaving us with several hundred duplicate incidents if it happens over a weekend.

**Help us reproduce the bug**
Version of the connector you are using:
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):
$defaultNewWorkItem = "ir"
$defaultIRTemplateName = "IR - Helpdesk Email Request"
$defaultSRTemplateName = "Default Service Request"
$defaultPRTemplateName = "Incident portal template"
$defaultCRTemplateName = "Standard Change Request"
$defaultIncidentResolutionCategory = "IncidentResolutionCategoryEnum.FixedByAnalyst$"
$defaultProblemResolutionCategory = "ProblemResolutionEnum.Documentation$"
$defaultServiceRequestImplementationCategory = "ServiceRequestImplementationResultsEnum.SuccessfullyImplemented$"
$checkAttachmentSettings = $false
$minFileSizeInKB = "9"
$createUsersNotInCMDB = $false
$includeWholeEmail = $true
$attachEmailToWorkItem = $true
$voteOnBehalfOfGroups = $false
$fromKeyword = "From"
$UseMailboxRedirection = $true
$Mailboxes = @{
    "facilities@company.com" = @{"DefaultWiType"="IR";"IRTemplate"="Company - IR - Maintenance Incident Request";"SRTemplate"="My SR Template";"PRTemplate"="My PR Template";"CRTemplate"="My CR Template"};
    "helpdesk@company.com" = @{"DefaultWiType"="IR";"IRTemplate"="Company - IR - Helpdesk Email Request";"SRTemplate"="Company - IT - Service Request Standard";"PRTemplate"="My PR Template";"CRTemplate"="My CR Template"};
    "old_hd@company.com" = @{"DefaultWiType"="IR";"IRTemplate"="Company - IR - Helpdesk Email Request";"SRTemplate"="Company - IT - Service Request Standard";"PRTemplate"="My PR Template";"CRTemplate"="My CR Template"};
    "companyAG@company.com" = @{"DefaultWiType"="IR";"IRTemplate"="Company - IR - Helpdesk Email Request - Global Announcements";"SRTemplate"="Company - IT - Service Request Standard";"PRTemplate"="My PR Template";"CRTemplate"="My CR Template"};
}

**Expected behavior**
Should process the email as normal and use the group name as the affected user.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?:
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 
Running SCSM 2016 on server 2012R2, using Task Scheduler to run the script every 2 minutes.

**Additional context**
The distribution group ZZAGroup (Company Global) is in the CMDB and the distribution address (companyAG@company.com is listed in the multiple inboxes configuration with a custom template to change the affected user to a dummy user with no return email (to prevent spamming the whole company with new incident notification emails). I added the companyAG to the multiple inboxes after the problem started as a possible fix.

**Comment by AdhocAdam** [comment]
So just to double check, going on your above example is helpdesk@company.com your primary SCSM inbox or a true secondary? The name leads me to believe it's primary, but the difference in IR templates leads me to believe it's truly secondary. I ask because this is something I myself tripped up testing awhile back as the primary _should not_ be included in the multi-mailbox config. In either case, just want to make sure I understand your example.

If it's truly the secondary, then @TomH-OpsDev and I have some thinking to do. However if this is something you have time to help breakpoint in a dev environment, we are entirely open to pull requests/discussion on the matter.

**Comment by infiniterecursion** [comment]
The primary is smnotifications@company.com and is not included in the list. We use hub transport rules for now to forward a copy from the other mailboxes to the smnotifications@ inbox. We are hoping to move to using aliases to the smnotifications address when we upgrade our Exchange environment later this year.

I use the same script in my dev environment but I currently have the multiple mailbox feature turned off there. However, the same emails that trip up the script in prod, do not trip it up in the dev environment with the multibox feature turned off.

I would be more than happy to help troubleshoot the issue where possible. I have a CS background, but am not as strong with Powershell as I would like to be, so maybe this will be an opportunity for me to learn a bit more :-)

**Comment by AdhocAdam** [comment]
> We use hub transport rules for now to forward a copy from the other mailboxes to the smnotifications@ inbox. 

The thing that caught my eye here was your use of "forward" above. Does your configuration differ from the [Wiki article](https://github.com/AdhocAdam/smletsexchangeconnector/wiki/Configuring-for-Multiple-Inboxes-(Email-Redirection,-not-Forwarding))?

**Comment by TomH-OpsDev** [comment]
Forwarding does not mark the headers correctly (the new mailbox becomes the TO address), so there will not be a match when the script is reading the email.  Redirection, on the other hand, preserves the original TO address in the header, allowing the script to determine which mailbox received the message, without having to connect to each one separately.

@infiniterecursion , you mention forwarding a **_copy_** of the message.  At least with Exchange, redirection does not remove the message from the inbox.  You have to have a second rule to delete the message from the original inbox (or move it, etc.) after redirecting, if you do not want to see it there anymore.  If you want to maintain a copy, then nothing needs to be done after the redirection.

**Comment by infiniterecursion** [comment]
Sorry, forward was a poor choice of words. The hub transport rule is doing a **copy** of the original message to the smnotifications mailbox. It does not modify the subject or the sent to address. I apologize for the confusion.

**Comment by infiniterecursion** [comment]
Tom, you are correct we are retaining the copied messages in the original mailboxes for now. When we do our Exchange migration later this year we will convert the other mailboxes to aliases for smnotifications.

**Comment by infiniterecursion** [comment]
Just wondering if you guys had any time to look at this?

**Comment by TomH-OpsDev** [comment]
As long as the TO is preserved, that should work.  I have only ever used redirection, however, and do not have the resources to be able to duplicate your setup.  The script reads the TO field when determining which template to apply, so that should be fine.

If it is not marking the message as read/deleting it, that suggests that the script is not getting to the end of the script, that some error is occurring along the way.  Are you by chance running this in SMA, to be able to look at the errors/outputs?

Also, if you use redirection instead of copy, that should accomplish your exact use case while also running the script in a manner that one of us can duplicate.  Would you be able to make that change?

**Comment by AdhocAdam** [comment]
I'm going to do my best to attempt to repro this within the week. In the interim - get a few of the messages you say work _incorrectly_ setup in your dev environment. Since you made mention that they work fine in dev with the setting off, just move them back to the dev inbox and mark them as unread. Finally, head over to the machine running the connector in your dev environment and perform the following...

1. Open the connector's PowerShell on the dev computer where you have it configured in PowerShell ISE or VS Code. You could do this remotely as well opening the script from your local machine and then reading over the network. The only difference is it saves you an RDP session.
2. Per v1.5 of the connector, breakpoint the following line:
https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L547
Breakpoints in ISE can be set by clicking anywhere on the line and hitting F9 which should turn the line red. In VSCode hover to the left of the line number and a red dot should appear. Click it to enable the breakpoint. This is the first line of the New-WorkItem function that is called when the email does not contain any known Work Item patterns in the subject.
3. Define/Configure the multi-mailbox features
4. As long as the message is unread in the inbox, run the connector within ISE/Code and after a couple seconds should bring you to Line 547 as breakpointed above. Now, you'll use F11 to step through each line. With your mouse, you'll be able to hover over the variables and see them get defined as the function moves forward.

Per your description of the issue, the Incident gets created but the Template does not apply. What I'm expecting to see the first "failure" on is:
https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L656

When you F11 this line, you'll be temporarily sent over the Get-TemplatesByMailbox function where I'm anticipating it will either return 0 Templates or _many_ Templates (hover over $TemplatesForThisMessage to confirm this or observe how the function itself is executing). In either case, when you finally f11 through and return back to the New-WorkItem function you'll see the Incident get created but the Template fail to apply. Which tends to explain your observation of "The Work Item gets created (and attachments added) but the template never applies."

https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L696-L707

As far as the message not getting deleted, I tend to agree with @TomH-OpsDev in that something between the initial read and the final delete is tripping this up preventing the delete as seen here in the mail processing loop:

https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L3461

Before attacking that, we need to identify what happening differently for you during this mid-execution.

**Comment by infiniterecursion** [comment]
Thanks guys, I will work on doing that testing this week. I've got some additional details here to hopefully help clarify my setup to make troubleshooting easier. I'll try to use as much correct terminology this time around as possible :-)

Primary workflow mailbox: smnotifications@company.com

Redirected mailboxes: 
helpdesk@company.com
old_hd@company.com
facilities@company.com

I am using an Exchange hub transport rule to generate a _copy_ of the original message from the redirected mailboxes into the smnotifications mailbox. This _does_ preserve the TO field in the message. Our Exchange environment is currently 2010 with almost current patches, we are in the midst of an upgrade to 2016 which should be done within the month. We have also had the problem occur when one of our help desk analysts dragged an email addressed to him into the smnotifications inbox folder (by dragging the original TO field for the analyst's mailbox was preserved).

I was able to run through the code as described above and have attached screenshots of the relevant areas. When I get to the line 656 I get 0 templates returned. The first error returned is in the second screenshot and appears to be related to the mailboxtouse variable.

![2019-07-24 09_44_14-Remote Desktop Manager Free  DSMMS](https://user-images.githubusercontent.com/4967133/61799742-a8163380-adf9-11e9-828a-a157d970885c.png)
![First Error](https://user-images.githubusercontent.com/4967133/61799762-af3d4180-adf9-11e9-830e-28f64595fc78.png)
![ReturnMailboxes](https://user-images.githubusercontent.com/4967133/61799779-b49a8c00-adf9-11e9-9e0d-b4a5c5fe8157.png)

**Comment by AdhocAdam** [comment]
Still trying to understand this one. But never the less two things:

1. I'm really hung up on the last screenshot and have been trying to work through in my head how Line 2337 was hit with _two_ inboxes. If you run this test again, I'm interested in seeing $MailboxToUse at Line 2300 and 2327 when they initially execute (e.g. as you step through it as opposed to after you've gotten down to 2337).

2. On the topic of Hub Transport rules (and terminology 😄). I can't rationalize why this approach wouldn't work, although as Tom and I have said it's never been tested. Either way, since you mentioned you're on Exchange 2010 I did some searching on Hub Transport rules for said version and found what I believe to be a a lot of folks saying essentially the same thing (I think).

**Version 1**
Apply rule to messages
Condition: Emails sent to SecondaryInbox
Action: Copy the message to PrimaryInbox
Result: The PrimaryInbox gets a copy of the message (because rule kicks in and simply CCs the PrimaryInbox)

**Version 2**
Apply rule to messages
Condition: Emails sent to SecondaryInbox
Action: Redirect the message to PrimaryInbox
Result: The PrimaryInbox gets the message as though it was the original recipient (this sounds _identical_ to what Tom and I have seen, just achieved through a Hub Transport rule)


Would you be able to verify which one of the above transport rules mirrors your configuration?

**Comment by infiniterecursion** [comment]
![HubTransportRule](https://user-images.githubusercontent.com/4967133/62731044-4821ae80-b9ef-11e9-9459-45fa47038c8e.png)

This screenshot should help to clarify the method used. Looks like I went with a BCC, though I don't know enough about Exchange to know how that my affect the message header. I'm going to be out of the office tomorrow, but I will run another step through for you when I get back on Monday.

**Comment by infiniterecursion** [comment]
Adam,
I've attached the requested screen shots of the areas you mentioned. Hope this helps in figuring it out.

![FirstBreakpoint](https://user-images.githubusercontent.com/4967133/63049266-44d26b00-bea6-11e9-9b22-39bbca070fa8.png)
![ValueOfToField](https://user-images.githubusercontent.com/4967133/63049274-4bf97900-bea6-11e9-8e42-92af5d6925e5.png)
![Line2300](https://user-images.githubusercontent.com/4967133/63049372-84995280-bea6-11e9-92c0-ca16d0f796c0.png)
![Line2300Part2](https://user-images.githubusercontent.com/4967133/63049380-87944300-bea6-11e9-9a04-e12d72061c2d.png)
![Line2317](https://user-images.githubusercontent.com/4967133/63049384-8b27ca00-bea6-11e9-8259-4b6bd5ca255b.png)
![Line2327](https://user-images.githubusercontent.com/4967133/63049385-8cf18d80-bea6-11e9-843c-ca6334d038dd.png)

**Comment by infiniterecursion** [comment]
Sorry for all the large screenshots, but I thought it'd be helpful if you could see where in the code I'm referencing.

**Comment by AdhocAdam** [comment]
No apologies necessary, because you're right - being able to see this stuff helps!

Alright I think I have something that explains the break and potentially proposes a way out of this while preserving all current functionality. I need to preface that it will take testing to be sure, but in the name of full transparency here we go!

1. Adding your distro group to the mailbox array - excellent thinking
2. When email enters the primary processing loop it loads up with the properties that are required to make the connector's various functions work.
3. When the custom PS Object $email is created within the loop it's done to shape a message to always have the same look any feel no matter how it comes in. From is always From, To is always To, etc. etc. If you breakpoint 3118 and highlight $message you'll see ALL of the properties that are originally obtained from the message including an interesting one - ReceivedBy.

https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L3118-L3132

However as you can see above, the ReceivedBy property is one that isn't even considered while forming the "new" email object that is created within the context of the connector. In fact, ReceivedBy equals the original receiving mailbox (so in your case, it would equal 1 of the mailboxes in your multiple mailbox configuration).

I believe if this property were to be introduced within the core processing loop seen above (as well as subsequent message classes) and Get-TemplatesByMailbox expanded with some additional if/else logic to account for it's existance, _but ignore_ if the ReceivedBy is the PrimaryInbox (which I believe would be the case in re-direction); that the connector could your meet your requirements while still maintaining the functionality others are used to.

If this is something you can get working in your dev environment then myself or @TomH-OpsDev should be able to cross-check our own current Multiple Mailbox config through re-direction. And then ultimatley, review a Pull Request to get this as stock functionality.

**Comment by infiniterecursion** [comment]
I'll look into making those modifications, though my Powershell skills are not as strong as I would like. Also, we have moved ahead with our Exchange migration and are now using the recommended setup in our production environment, and the issue is still happening there, but without the duplicate message loop.

**Comment by infiniterecursion** [comment]
I did a little testing and can confirm the ReceivedBy field will match the ToRecipients field in a message sent to one of the redirected mailboxes, but the ToRecipients field will be different when the message was sent to a distribution group that included the redirected inbox. I added a brief bit of logic at line 3119 to check if the fields are equal and it not, use the ReceivedBy field to create the To field in the message object. I've included the code snippet below.

Alternatively, you could just always assign ReceivedBy to the To field as it will always be correct for the receiving mailbox, except in the case of someone dragging a message from their own mailbox into the workflow inbox which this modification does not correct for.

Also, I did not modify the sections for dealing with signed or encrypted messages as we have not yet implemented those in our environment.

I apologize for the quick and dirty work, my boss did not give me a whole lot of time to devote to fixing this so I focused on the minimum needed to get this to work in our environment.

Starting at line 3119:
`if ($message.ReceivedBy -ne $message.ToRecipients)
        {
            $email | Add-Member -type NoteProperty -name To -value $message.ReceivedBy
        }
        else
        {
            $email | Add-Member -type NoteProperty -name To -value $message.ToRecipients
        }`

**Comment by AdhocAdam** [comment]
Quick, dirty, right, or wrong - you sir have accomplished something here and that's what matters!

I'm trying to wrap up v1.6 _and_ v2.0 this month, but if I get the time I'll try to test this out with the other features. But overall, I really like the idea/line of thinking here and am keen to integrate.

_If_ however you can make the Pull Request on your account, we can have a sandbox to actively work this in. Just make sure you upload a sanitized version of the connector and not your own (i.e. since that would contain accounts, mailboxes, etc. which you probably don't want 😄 ) Or just Fork the repo, make the edits, and then you don't have to deal with uploading.

**Comment by infiniterecursion** [comment]
Thanks for the words of encouragement!

I opted for the fork option, and created a pull request for you (hopefully it's done right, was my first PR).

**Comment by AdhocAdam** [comment]
I had to re-read this a couple times to make sure all was accurate and I _think_ I've got it. In short, you're close. I threw together a quick picture to illustrate what needs to happen. But the idea is this -

When you Fork a repository, you copy _all of it_ over to your account. That means you get all of the "branches" of the repo. Think of Master branch as the stable iteration of the project. All of the branches that derive out from it are more analogous to ideas, fixes, enhancements, etc. They could be _anything_ but they are ever so slight derivatives from said Master branch. With a Pull Request, we can pull the changes from a downstream branch up into the Master branch.

But obviously - you and I could be working at entirely different paces, doing entirely different things (this why that 6th thing in the picture differs between us). Hence the whole concept of branches comes in handy. Because they are each their own unique concept. In the case of the Pull Request you've raised, you've made an edit to _your_ Master branch and are requesting a merge into the Master branch of my instance of the SMlets Exchange Connector. It's not "technically" wrong, I mean GitHub clearly allows it right? But in this case, should this be approved it's instantly written to the production/public SMLets Exchange Connector.

The following picture illustrates what needs to happen.
1. You have the Fork. Check!
2. You should make your own branch from your Dev branch on your repo. Call it something like "Multi-Mailbox Enhancement" (e.g. Fix 6 in the picture) or whatever you'd like. You can do this by navigating to your repo, changing the branch to "dev" and then begin typing a new branch name. GitHub will show you what the branch is spawning from
3. Make your changes on said branch
4. Submit a Pull Request from that branch to my Dev branch.

As some examples, here's a recent Pull Request I made from a recent Feature Branch into Dev.
https://github.com/AdhocAdam/smletsexchangeconnector/pull/143

Or check out this example from @justinkwork
https://github.com/AdhocAdam/smletsexchangeconnector/pull/124


![pullrequestexample](https://user-images.githubusercontent.com/6636040/64313285-d21e5200-cf70-11e9-9504-3c5ce5ec71e3.png)

Even as the repo's Author, I make Pull Requests from downstream branches into Dev so I can review the PowerShell for each feature/fix/enhancement I make. Eventually, a Pull is made to roll dev up into the Master branch. Here's an example of such a Pull Request - https://github.com/AdhocAdam/smletsexchangeconnector/pull/113. So all of the individual edits happens on branches that spawn from dev. Those ideas then all individually roll into dev as seperate PRs. Then a single PR is made from dev to master when the next version comes out.

This absolutely took me some practice/getting used to but eventually it all started falling into place. The good news is you have unlimited tries, no penalty for learning!

**Comment by infiniterecursion** [comment]
Ah, yes that all makes sense. Sorry for using the master! I didn't realize the fork will fork all the branches. Let me go make another PR real quick.

**Comment by AdhocAdam** [comment]
No worries!

**Comment by AdhocAdam** [comment]
Looks like you've nailed it. Closed your original PR (housekeeping) so we can work on the new branch/pull.

**Comment by infiniterecursion** [comment]
So, while setting up a new mailbox for some notification emails today I discovered that sometime after my last post the behavior in our Exchange environment has changed and the ReceivedBy field is now set to the workflow mailbox instead of the originating address. I've been talking with my Exchange admin and we can't come up with a good reason for this new behavior as there haven't been any changes to the environment recently. We are currently using Exchange 2016 CU 13 and may try to update to CU 14 this weekend to see if anything changes. I'll also check with our WSUS server to see if any patches have been added to the server that my affect things as well.

**Comment by infiniterecursion** [comment]
@AdhocAdam 
I don't want to be a nag, but I was wondering if you had seen my previous comment and had any thoughts on this. As it stands, everything being addressed to a secondary mailbox is just being dumped into the workflow mailbox regardless of incoming address.

**Comment by AdhocAdam** [comment]
Apologies on my less than prompt reply @infiniterecursion. v2 and SCSMOutOfOffice really took my focus away this last month.

So unfortunately this really goes to environment specific questions that I'm not sure how to begin to diagnose. That said, all I can offer is general questions and guesses on this front based on what you're describing as they are probably not SMLets Exchange Connector related. While this begins to venture slightly off course from this thread I'll try my best -

**Scenario: When a Secondary Mailbox receives mail, SMEXCO interprets the received by as the Primary Inbox**

- Per your previous comments, you're using Transport Rules to manage Secondary Mailbox mail flow. But in this case, somewhere along the way the ReceivedBy is now the Primary Inbox as opposed to the Secondary. You also said there have been no environment changes, which I'm going to take to mean Exchange...but what about Active Directory? What's jumping to mind here is the alternative way to configure mailbox redirection as seen over [here ](https://github.com/AdhocAdam/smletsexchangeconnector/wiki/Configuring-for-Multiple-Inboxes-(Email-Redirection,-not-Forwarding))on the wiki. Instead of running a Set, can you perform a Get against the secondary mailbox users and retrieve their TargetAddress property? I obviously don't need to know what it is so much as you just need to make sure this hasn't been altered potentially impacting Exchange flow.

**Comment by infiniterecursion** [comment]
When we did our Exchange switchover to 2016, we converted the helpdesk mailbox over to a shared mailbox instead of a full user mailbox. I'm going to make sure the setup is duplicated in our dev environment and will run some tests. I expect to find the behavior in the address fields with a shared mailbox differ from the address field when a distribution group is used. I'll report back later today with my findings.

**Comment by infiniterecursion** [comment]
Ok, after some testing I've found an underlying logic issue that may be relevant here. In the first screenshot below is a normal email that is sent directly to a workflow mailbox. In the message details, it is possible to see the ToRecipients and ReceivedBy fields contain the same value which is the workflow mailbox. This is all standard, expected behavior and is included as a control sample.
![Test-Workflow-Mailbox-Direct-Email-Message](https://user-images.githubusercontent.com/4967133/69558103-a9a56300-0f75-11ea-80a1-4e235d1952ff.png)

The next screenshot is for an email message that is sent to a different mailbox but delivered to the workflow mailbox using a Hub Transport rule that performs a "Redirect the message to" action. In this case, the ToRecipients field contains the address of the mailbox the email was directed to and the ReceivedBy field contains the address of the workflow mailbox. This also seems to follow with expected behavior for using the Multiple-Mailbox feature and should produce the correct results when processing the message.
![Test-Shared-Redirected-To-Workflow](https://user-images.githubusercontent.com/4967133/69558696-aa8ac480-0f76-11ea-8385-e4ed11f6b282.png)

This screenshot shows a message that is sent to a dynamic distribution group that contains all mailboxes in the Exchange environment (including service accounts). In this example, the ToRecipients field contains the address of the distribution group, but the ReceivedBy field still contains the workflow mailbox. This is where I put the logic in my pull request to correct the action. It does a compare between the two fields and if they are different, uses the ReceivedBy instead of the global group. This seemed right at the time, but the problem with my logic becomes apparent in the next example.
![Test-Workflow-Mailbox-Global-Distribution-Group-Email](https://user-images.githubusercontent.com/4967133/69571036-1d079e80-0f8f-11ea-8e9b-b282a92d8c55.png)

This is where it gets tricky. In this screenshot, a global distribution email has been sent to a redirected mailbox. The ToRecipients field shows the distribution group name, and the ReceivedBy field shows the workflow mailbox. This means if we are pulling from multiple mailboxes and an email gets sent to each of those mailboxes from a global distribution group, the script has no way to discern which mailbox the message was delivered to.
![Test-Shared-RedirectedToWorkflow-GlobalMessage](https://user-images.githubusercontent.com/4967133/69571406-00b83180-0f90-11ea-9256-369bbc305c43.png)

At this point, I can't think of a way to program the logic for this into Powershell since there isn't anything to go from in the last example. I've been talking with our Exchange administrator and I think we are going to solve this for now by converting our dynamic distribution groups to groups that read a particular LDAP OU, allowing us to filter out service accounts from the recipients list. I'm not keen on fixing a bug by filtering out the conditions of the bug, but that seems to be the best resolution for the time being.

This whole situation has me wondering whether we should just have a different copy of the script to read each mailbox individually similar to the stock Microsoft connector.

**Comment by AdhocAdam** [comment]
**First**
![reaction](https://user-images.githubusercontent.com/6636040/69599906-54e50500-0fd4-11ea-938a-c91c216d721a.gif)

**Second**
Looks like I need to read **all of the EWS documentation** to see if there is a way out of this as I can tell you right now, I truly do not know. I can confidently say this scenario genuinely never occurred to me (and I'm guessing @TomH-OpsDev as well, but don't want to speak for him). In the interim, your incredibly detailed troubleshooting has given me an idea that:

- I have not tested
- I have no way of measuring/estimating the performance hit to Active Directory and the connector
- Perhaps with more logic we could reasonably deduce redirection didn't happen (but not sure we can prove it for your aforementioned reason).
- Needs to be built out more to support CC recipients
- Should fit into the into the first foreach logic of Get-TemplatesByMailbox

Basically, the idea is to identify all of the Distribution Groups in ToRecipients. Then foreach one of them, Get their AD Group equivalent, then get all of the AD Group Members, then identify the member that matches one of the mailboxes in the $mailboxes variable. I've added the recursion because I don't know how deep the mailbox could be nested in a group, but that means it potentially comes at a cost of waiting for an item to only _possibly_ enumerate. I'd be interested to know your thoughts on this?

```powershell
    $usersInDistroGroup = @($message.ToRecipients | ?{$_.MailboxType -eq "PublicGroup"} | %{Get-ADGroupMember -Identity $_.Name -Recursive} | %{Get-ADUser -Identity $_ -Properties emailaddress})
    $userInDistroMatchingSecondaryMb = (Compare-Object -ReferenceObject ($Mailboxes | select keys -ExpandProperty keys) -DifferenceObject $usersInDistroGroup.emailaddress -IncludeEqual | ?{$_.SideIndicator -eq "=="} | select -first 1).InputObject

    $redirectedMailboxToUse = $Mailboxes | %{$_.GetEnumerator()} | ?{$_.Key -eq $userInDistroMatchingSecondaryMb}
    $redirectedMailboxToUse
```

But to your final point -

> I'm not keen on fixing a bug by filtering out the conditions of the bug, but that seems to be the best resolution for the time being. This whole situation has me wondering whether we should just have a different copy of the script to read each mailbox individually similar to the stock Microsoft connector.

I'm of a similar mindset that this isn't ideal and surely there has to be a way around this. As you said, multiple scripts would work as it would entirely skip the problem you've highlighted entirely. But if you're willing to experiment with the above, I'm certainly willing to continue to work together on this.

**Comment by infiniterecursion** [comment]
Thanks for the compliments!

I did a little digging and cannot find any detailed information on the search speed for Get-ADGroupMember or even the algorithm used so I'll have to make the basic assumption that they are using something relatively common and efficient like binary search. Based on that assumption we can assume a worst-case search speed of log n where n is the number of items in the group being searched. This is not a bad amount of time ~13 look ups for a 10,000 item list. However, I did find documentation indicating that GetADGroupMember only handles groups of 5,000 items or smaller which could be an issue in a larger environment. I did see some references to the ADSI cmdlets being used to bypass this limitation but I don't know much beyond that.

I'll do some thinking on this over the holiday weekend and see what other ideas I can come up with.

**Comment by infiniterecursion** [comment]
Sorry for the delayed response, we are close to going live with a new ERP system and things are busier here than usual. 

After spending some time thinking about this I'm wondering if it might be easiest to implement an array that contains a blacklist of email addresses that are problematic and can be ignored by the connector. That would allow us to at least take care of the logic flaw regarding redirected messages from distribution groups.

I think in the long term, the best solution may involve using separate shared mailboxes and have the script read each mailbox directly rather than using a single workflow mailbox. This would have the advantage of being able to use shared mailboxes that do not require the creation of AD user accounts, and (possibly in the future) the ability to customize features and settings on a per-mailbox basis. In addition, it would also eliminate the need to look at any data field other than the ReceivedBy.

**Comment by AdhocAdam** [comment]
A blacklist of email addresses...hrm...

I think I get what you're suggesting, but I am slightly concerned about the implication of that. Because that may move the connector into the territory of perceived spam handling. But I'm also willing to admit that I could just be hung up on the phrasing of it and it's a complete nonissue.

So assuming I'm following you here, you'd have an array of addresses (presumably distro groups) that are skipped entirely when processed? Or they are exceptions? I guess I'm struggling to understand how/when/where the correct template is applied in this case.

As far as the separate shared mailboxes go, it's certainly doable but would require some refactoring in v2.x as there is only a single Settings MP with potentially multiple mailboxes that could be defined. So the **scripts** would need some way of understanding which mailbox belongs to which script. This feels like it could introduce some administrative overhead.

**Comment by infiniterecursion** [comment]
Yes, please forgive my phrasing. Blacklist was probably not the best word here. I think we are thinking along the same lines of an array of addresses to just blindly ignore (or ignore and delete the message). The intention here is not for spam filtering, but to avoid the original looping issue that happens with distro group emails since we can't reliably use the ToRecipients or the ReceivedBy fields, though by ignoring distro group emails, I think we could come up with a logic flow that would allow us to use the ToRecipients and ReceivedBy to make using shared mailboxes more reliable.

As for the shared mailboxes, my vision of a perfect world would be to use one script but process multiple shared mailboxes directly without using a central workflow mailbox. This may allow some options to be moved to a per-mailbox option rather than a global option per script. I realize this may require significant refactoring so I'm not holding my breath here, though if v2 is storing the configuration options in a MP, then maybe adding settings on a per-mailbox basis won't be too bad as they aren't being stored in the script anymore but it does increase the complexity significantly.

**Comment by infiniterecursion** [comment]
Closing issue. We were able to resolve this on the Exchange side of things by updating our dynamic distribution group to use only end-user OU's to generate the list of users, leaving out our service accounts OU which contains the service mailbox for the exchange connector. This allows us to keep the service mailbox out of most of the campus-wide distribution groups that kept hanging up the script and screwing up our processing logic.

Sorry for it not being the most elegant solution but until MS changes how Exchange handles the ToRecipients and ReceivedBy fields there aren't many other options.
