### ISSUE TITLE
Dynamic work item assignment not functioning as expected

### ISSUE THREAD

**Issue by bennyguk** [AdhocAdam/smletsexchangeconnector#188]
**Describe the bug**
When selecting the option for OOOVolume, the Dynamic Analyst Assignment function does not seem to respect the Out of Office status of the analysts in the support group, and the Get-AssignedToWorkItemVolume function seems to work in reverse; i.e. the analyst with the most work items assigned gets the new work item.

**Help us reproduce the bug**
Version 2.2 of the script from the releases zip file.
Options enabled:
- Attach Email to Work Item
- Process Meeting Requests
- Update Work Items missing [Work Item]
- Change Incident Status on Incidents based on who replied
- Dynamic Incident Assignment - OOOVolume
- Enforce Maximum Attached Size per individually defined Work Item settings
- Enable Cireson Integration
- Enable Knowledge Base Suggestions
- Enable Request Offerings Suggestions
- When Suggestions are sent, set the First Response Date

**Expected behavior**
If an analyst in the Work Item template's support group is either OOO or has more Work Items assigned that the other Analysts in the support group, then I would expect them not to have the new Work Item assigned to them.

**Location and Environment**
Where are you running this from? Powershell ISE as the workflow service account on the Management server.
What SCSM version are you running? 2019 RTM

**Additional context**
I have troubleshooted this problem myself and the following code changes have fixed the OOO functionality in my environment.
The original code:
`$userToAssign = $supportGroupMembers | Where-Object {$supportGroupMembers.OutOfOffice -ne $true}`

New version:
`$userToAssign = $supportGroupMembers | Where-Object {$_.OutOfOffice -ne $true}`

The Get-AssignedToWorkItemVolume function seemed to be sorting in the wrong way in my environment, so I simply needed to remove the '-Descending' parameter.
The original code:
`$userToAssign = $supportGroupMembers | Where-Object {$supportGroupMembers.OutOfOffice -ne $true} | foreach-object {Get-AssignedToWorkItemVolume -SCSMUser $_} | Sort-Object AssignedCount -Descending | Select-Object SCSMUser -ExpandProperty SCSMUser -first 1`

New version:
`$userToAssign = $supportGroupMembers | Where-Object {$_.OutOfOffice -ne $true} | foreach-object {Get-AssignedToWorkItemVolume -SCSMUser $_} | Sort-Object AssignedCount | Select-Object SCSMUser -ExpandProperty SCSMUser -first 1`

These changes have made the Dynamic Work Item Assignment work for me, but i'm not sure if this is because of a configuration issue that I have created in my environment or something else I've done wrong because nobody else seems to have reported this issue?

**Side notes**
I have noticed that the workflow in the scsmoutofoffice Management Pack seems to have the same issue in that it seems to pick analysts that are OOO. Perhaps the some of the code is shared between these projects?

Amazing piece of work BTW. I only just recently stumbled on it by complete accident and very glad I did.

**Comment by AdhocAdam** [comment]
Well first thing's first - I truly cannot thank you enough for this amazingly detailed breakdown! I have no follow up questions here so give me a few days to test and I'll get back to you.

Also, I'm glad you found this connector as it sounds like based on other things you have enabled its already helping you out. So thanks!

**Comment by AdhocAdam** [comment]
Hey there @bennyguk -

Alright so quick sanity check and you have absolutely found a valid break with respect to Volume based Out of Office assignment. Per your comment above, the Where-Object syntax on the pipeline should be using the $_. Since I'm all about giving credit where credit is due - if you can fork the repo, create a branch from dev, edit, and open a pull request with this change you'll become an official contributor to the SMLets Exchange Connector repo! But if that sorta thing doesn't interest you I can make the change as well. Of course - if you're interested in this but unfamiliar with the process I can certainly help walk you through it. Point is - you've found an issue. Let's address it!

> The original code:
> ```powershell
> $userToAssign = $supportGroupMembers | Where-Object {$supportGroupMembers.OutOfOffice -ne $true}
> ```
> New version:
> ```powershell
> $userToAssign = $supportGroupMembers | Where-Object {$_.OutOfOffice -ne $true}
> ```

However in regards to the Get-AssignedToWorkItemVolume function, this isn't something I can reproduce. Take the following example using regular ole PowerShell. Do you get the same results? Different?

```powershell
$array = 2, 4, 1, 10, 3
$array | Sort-Object -Descending
10
4
3
2
1
```

But if we remove the -Descending switch...
```powershell
$array = 2, 4, 1, 10, 3
$array | Sort-Object
1
2
3
4
10
```

Lastly in regards to the scsmoutofoffice management pack. Yes they do share a few similarities, here's the PowerShell that makes up the Workflow for the management pack around Service Requests. It's the _near identical_ PS for the other Work Item classes. So I'm sure you can probably appreciate how this block of PowerShell changes very little between Work Item Classes within the MP. Class aside, we're still working with:

- the $_.OutOfOffice property that this MP introduces that makes it possible for the SMLets Exchange Connector reference
- SMLets **especially** because SMLets provides us the ability to work with historical Relationships where as the stock cmdlets do not (unless this changed in SCSM 2019). A key item since the MP needs to be able to undo an assignment.
- The -descending switch

```powershell
import-module smlets
$srClass = Get-SCSMClass -name "System.WorkItem.ServiceRequest$"
$assignedToRelClass = Get-SCSMRelationshipClass "System.WorkItemAssignedToUser$"
$serviceRequest = Get-SCSMObject -class $srClass -filter "Name -eq '$Id'"
$assignedToUserRelationships = Get-SCSMRelationshipObject -BySource $serviceRequest -Filter "relationshipid -eq '$($assignedToRelClass.id)'" | Sort-Object LastModified -descending | Select-Object -First 2
$assignedToUsers = $assignedToUserRelationships | foreach-object {Get-SCSMObject -id $_.TargetObject.Id}
if (($assignedToUsers[0].OutOfOffice -eq $true) -and ($assignedToUsers[1]))
{
    #New Assigned To is Out of the Office, Assign back to previous
    Remove-SCSMRelationshipObject -SMObject $assignedToUserRelationships[0]
    New-SCSMRelationshipObject -Relationship $assignedToRelClass -Source $serviceRequest -Target $assignedToUsers[1] -bulk
}
if (($assignedToUsers[0].OutOfOffice -eq $true) -and !($assignedToUsers[1]))
{
    #New Assigned To is Out of the Office AND Previous Analyst was never set
    Remove-SCSMRelationshipObject -SMObject $assignedToUserRelationships[0]
```

If you want to see this and more of that MP the above lines can be seen in the unsealed MP on thescsmoutofoffice repo over [here](https://github.com/AdhocAdam/scsmoutofoffice/blob/98bade2ae1c5b90885152b6849e7aaf1838769f5/UnsealedManagementPacks/AdhocAdam.WorkItemAssignmentPrevention.OOO.xml#L151-L166)

**Comment by bennyguk** [comment]
Hi Adam, I'm so glad that this has been useful. At the moment the script is in testing before we go live, but it shouldn't be long before we do.
I would be delighted to help in any way that I can, so I'll create a pull request as you have suggested. It's been a while, so i'll give it a go and let you know if I need some help.

I'm not in the office for a little while now, but as soon as I am back I will do some more testing of the Get-AssignedToWorkItemVolume function and let you know how I get on.

Thanks,

Ben

**Comment by AdhocAdam** [comment]
Would you mind doing the same for v1.x?

**Comment by bennyguk** [comment]
No problem. Just sent the pull request,

Thanks,

Ben

**Comment by AdhocAdam** [comment]
Thank you sir!

**Comment by bennyguk** [comment]
Hi Adam, I've had a little bit of time to do some more testing today and I can confirm that I get the same results as you with the basic Sort-Object PowerShell test.

To get a little more information on what is happening in my environment, I've broken the code down a bit and added a couple of lines of code to the Set-AssignedToPerSupportGroup function so that the `elseif $DynamicWorkItemAssignment -eq "OOOvolume` statement is like this:

`function Set-AssignedToPerSupportGroup ($SupportGroupID, $WorkItem)
{
    #get the template's support group members
    $supportGroupMembers = Get-TierMembers -TierEnumID $SupportGroupID

        #based on how Dynamic Work Item assignment was configured, set the Assigned To User
        if ($DynamicWorkItemAssignment -eq "volume")
        {
            $userToAssign = $supportGroupMembers | foreach-object {Get-AssignedToWorkItemVolume -SCSMUser $_} | Sort-Object AssignedCount -Descending | Select-Object SCSMUser -ExpandProperty SCSMUser -first 1 
        }
        elseif ($DynamicWorkItemAssignment -eq "OOOvolume")
        {
            $userToAssign = $supportGroupMembers | Where-Object {$_.OutOfOffice -ne $true}

            #Debugging 
                write-host "Analysts that are not OOO:"$userToAssign   
                          
            $userToAssign = $userToAssign | foreach-object {Get-AssignedToWorkItemVolume -SCSMUser $_}
            $userToAssign = $userToAssign | Sort-Object AssignedCount -Descending

            #Debugging
                $userToAssign | format-list

            $userToAssign = $userToAssign | Select-Object SCSMUser -ExpandProperty SCSMUser -first 1

            #Debugging
                write-host "Selected analyst:" $userToAssign
.....`

The results with the -Descending parameter are:
`Analysts that are not OOO: Tom  Marc  Ben

SCSMUser      : Ben
AssignedCount : 44

SCSMUser      : Marc
AssignedCount : 11

SCSMUser      : Tom
AssignedCount : 8

Selected analyst: Ben`

And without the -Descending parameter:

`Analysts that are not OOO: Tom Marc Ben

SCSMUser      : Tom
AssignedCount : 8

SCSMUser      : Marc
AssignedCount : 11

SCSMUser      : Ben
AssignedCount : 45

Selected analyst: Tom`

As far as I can see from the results above in my environment, it would make sense that we would want the results to be in ascending order so that `Select-Object SCSMUser -ExpandProperty SCSMUser -first 1` will select the analyst with the fewest AssignedCount because they are the first in the array. 

The results seen consistent with the basic Sort-Object test, or am i getting my wires crossed?

Anyway, I hope this is useful.

Thanks,

Ben

**Comment by AdhocAdam** [comment]
It would appear that I in fact am the one who has the wires crossed! As you rightly point out, I'm using -descending | select first 1 but I should really be performing one of the following:
- -descending | select -last 1
- | select -first 1

I'll have to test to be sure, but I'm _pretty_ sure that's what is the issue here. In either case, thank you!

**Comment by bennyguk** [comment]
Thanks Adam, i'll do that now.
