### ISSUE TITLE
Preserve custom org changes through versions and patches

### ISSUE THREAD

**Issue by AdhocAdam** [AdhocAdam/smletsExchangeConnector#21]
Raising/Summarizing this on behalf of Tom -

While management packs make upgrades seamless and preserve various settings, upgrades of this connector introduce varying levels of rework in order to preserve changes across upgrades, patches, etc.  It seems perhaps the best way to cut down on this rework is to feature a path style variable that loads organization specific functions and modules. Then creating events that can be hooked into such as "BeforeCreate", "AfterCreate", "BeforeUpdate,", "AfterUpgrade" so those specific features can continue to be used and the connector can grow in modularity.

**Comment by TomH-OpsDev** [comment]
Idea for the approach:

Create a separate PS file that contains empty functions that are named after "events" within the script, such as "Invoke-BeforeCreate" or "Invoke-AfterUpdate".

Load this file in smletsExchangeConnector (If running from task scheduler.: . C:\smletsExchangeConnector\customEvents.ps1 / If running in SMA: first import this file as another script runbook, call it like .\customEvents.ps1 if that is its runbook name).

Throughout the main script, call the names of these functions at important points in the script execution.   If there is nothing in them, nothing happens.

Users of this script can add their own code inside of these functions in the other file, and they will run consistently as new versions smletsExchangeConnector are implemented.

**Comment by TomH-OpsDev** [comment]
Assigning myself since I started the first pass at this--but review/feedback/contribution are all welcome!

The decision regarding what point in the script qualifies as the "event" that we are trying to capture is somewhat arbitrary until it has been used by someone.  I only have a couple proprietary functions I am testing in my environment.

We may find that some of these do not provide clear value and can be removed for simplicity's sake, too.
