### ISSUE TITLE
Regional decimal delimiter when validating Min File Attachments size

### ISSUE THREAD

**Issue by alexaxb** [AdhocAdam/smletsExchangeConnector#217]
**Describe the bug**
The textbox validation for File Attachments expects a dot as decimal delimiter. However, in some regional settings (Swedish for example) the decimal limiter is a comma. So everytime the Settings form is opened, the console will use a comma in the File Attachments value textbox (since that is the regional setting in windows) and the validation will throw a red star cause it cannot find a dot in the textbox.

**Help us reproduce the bug**
Version of the connector you are using: 2.3
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):

**Expected behavior**
The validation needs to look for the current decimal delimiter that is used in windows.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: Task Scheduler
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 2019

**Additional context**

**Comment by AdhocAdam** [comment]
I went to Region settings, Additional Settings, changed the Decimal symbol to a different character, and then re-opened the SCSM Console. I was unable to save the form as the validation regex in the XAML is only looking for numbers and .

https://github.com/AdhocAdam/smletsexchangeconnector/blob/1ec9a6ccc89cd302d5f8fda6f73ef160e8276923/ManagementPack/2016/SMLetsExchangeConnectorSettingsUI/Forms/FileAttachmentForm.xaml#L18

Thank you for bringing this up and making me just a little less ignorant on this front. I look forward to overcoming this challenge 😄

**Comment by alexaxb** [comment]
Shouldn't this work as regex: ^^[.,][0-9]+$|^[0-9]*[.,]{0,1}[0-9]*$
However, I'm not sure if there are more decimal chars out there :D

**Comment by AdhocAdam** [comment]
I had the **identical** thought process. "Oh I'll regex for . _or_ ," and then "But there are probably more characters out there by virtue of what Alex has said."

**Comment by AdhocAdam** [comment]
Doing some research and came across [this Microsoft doc](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.tryparse?view=net-5.0) on the topic. If you scroll down to the Examples section, it deals with what appears to be the core of what you've raised.

While I haven't attempted anything yet, I'm thinking perhaps the regex simply get's dropped from the UI and then the commit in AdminSettingsWizardData.cs performs the validation. Something to the effect of:
- Get the current culture
- Try to parse the value based on said culture
- Some IF logic to determine whether or not conversion occurs
- Save

If the validation doesn't pass it just sets a default value like 5.0 or something. That way the pwsh can continue to run/process like it has since v1. Again, not committed to anything yet but this feels like a path forward.

**Comment by AdhocAdam** [comment]
This fix will be released via #226 shortly
