### ISSUE TITLE
Create incidents with all properties/relationships rather than bit by bit

### ISSUE THREAD

**Issue by glennguy** [AdhocAdam/smletsExchangeConnector#486]
**What's your idea? Go!**
Provide a clear and concise description of what you want the connector to do that you think everyone could benefit from.

In the section starting [here](https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L1134) the incident is created, then piece by piece things such as templates, affected user etc. are updated.
You can see how this plays out in the history tab of the incident, with multiple entries created for the incident creation process (compared to MS connector).

*Why is this a problem?*
Notification subscriptions.
It makes the 'When an object of the selected class' type of notification much less useful. In my case I have several different notification email templates depending on the tierqueue set, which in turn is set by an incident template. The subscription workflow is never triggered because in reality the tierqueue is set after incident creation.

*Possible workaround:*
I can set a subscription to track changes from null tierqueue to whatever I want as the target, but this would probably have unintended consequences when the users get their hands on it.

*Suggested solution*
Create the IR in the complete target state, similar to the behavior of MS Exchange Connector. Maybe this would have a performance impact? Hoping that at least this is something viable, and could be a selectable option if there's a tradeoff?

**Comment by BrettMoff** [comment]
This issue impacts the notify analyst settings for "Ignore default support group on create" as when the work item is created it does not have the support group set.
It would be beneficial for the initial creation of a work item to be done so with a template. That way the admin can choose what properties should be set to what at initial creation of the work item.
Additional properties and relationships can be modified after the fact (Such as relating the user that sent the email, attaching the email as a file, and any other properties that are configured within the connector.

![smletsexchangeconnector-Template](https://github.com/user-attachments/assets/4bc84025-8438-45ac-a17e-a417f06ae1fb)

**Comment by AdhocAdam** [comment]
There is some history here as to why this wasn't done:

- The native connector made use of two Templates, one for Create and one for Update. While the Create/default was easier to understand, the Update portion occasionally led to misconfiguration (e.g. setting a support group, and then "undoing" potential re-assignments that had happen since create). Once you learned this, you didn't forget it and made changes accordingly. But it was part of my original notes when drafting the PowerShell as something that could just be avoided entirely if "you didn't need to manage Templates"

- Going the PowerShell route, the PowerShell syntax I believe lends itself incredibly well to quickly understanding; even if you aren't all that familiar with PowerShell. At the time, I recall Jeffrey Snover saying on the topic of why PowerShell has the syntax it does was to the effect of "If you have to look at a script at 2am, you want it to make sense." That said, when it came to working with SCSM Type Projections for Templates, it was _less_ clear (in my opinion) than any other PowerShell syntax at the time. Take for example the Type Projection used to [construct a comment](https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L3003-L3020) in the connector. In the spirit of this, plus a few other reasons seen below. It drove the creation of creating a Work Item, and then adding values each step of the way.
    - An original goal of the connector which was being able to modify the processing logic to suit your needs. Apart from being written in PowerShell, being open source makes this possible
    - A feature that was introduced very early on in the name of customizations was [Custom Events](https://github.com/AdhocAdam/smletsexchangeconnector/blob/primary/smletsExchangeConnector_customEvents.ps1). It allows modifications to the core processing logic before and after specific events, and no less is preserved throughout upgrades. Rather than do all of this with Templates, in memory and with less than obvious PowerShell. It could be written to SCSM each step of the way. The customized code would be able to be direct and precise in the changes it was making. Over the years it led to the creation of _more_ Custom Events to have more processing points to interact with
    - [Send-EmailFromWorkflowAccount](https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L3422) was a function that took advantage of already having a connection established with Exchange. While used in a few of the connector's features, it is also available to use within [your own Custom Events](https://github.com/AdhocAdam/smletsexchangeconnector/wiki/Custom-Events-Examples#invoke-aftertake)

- The code to apply a template has changed over the years, but it has always been something that was borrowed. What started as 3 functions [borrowed entirely](https://blog.ctglobalservices.com/service-manager-scsm/mme/set-scsmtemplatewithactivities-powershell-script/) to 2 functions that [leverage a third unique to the connector](https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L3806), always required the Work Item to exist. This was something early on I wanted to ensure, so that regardless of possible issues in code and/or the Template itself (which could be anything) - the Work Item and its attachments would be **_guaranteed_** to be created.


That said, while I have no plans to change or alter this functionality. I am more than open to reviewing pull requests on this topic.

**Comment by glennguy** [comment]
Thanks heaps for the detailed background and explanation Adam, and I get that it's done in a way which is much safer and easier to read. For now with the constraints I'm working with and the plethora of existing subscriptions, I'll have to push forward with MS' lovely offering. But, if I get the opportunity I'll look at customising the script to work in this alternate way and also contributing back with a PR.

Thanks again!
