### ISSUE TITLE
[take] of Manual Activities Doesn't Assign Activity Implementor

### ISSUE THREAD

**Issue by rameuses** [AdhocAdam/smletsexchangeconnector#56]
We've added a custom Support Group class to Manual Activities an use Cireson's Notify Analyst application to send the support group a notification of assignment. Responding to the e-mail with the [take] comment enters a partial note in the note field of the MA but it doesn't assign the MA to the sender.

**Comment by AdhocAdam** [comment]
Sounds like a great use case and enhancement here. I like it!

What logic do you think makes the most sense here? If anything, it's just another configuration variable that would control this:
- If the Implementer is null, Take
- Regardless if the Implement exists or not, Take
- Optionally enforce Support Group in the vein of #27 

Otherwise, seems relatively easy to add this logic. Just another ELSEIF within the MA update section.

**Comment by rameuses** [comment]
For sure, take if null. 

A setting for take if not null and enforce support group membership would be nice too.

**Comment by AdhocAdam** [comment]
Will split Support Group portion of this into another FR as it will require a new and currently unwritten means to handle this rather popular class extension for MA.

Introduced _basic_ [take] functionality akin to IR/SR on #50

**Comment by AdhocAdam** [comment]
Introduced enhanced [take] logic with optional Support Group enforcement akin to IR/SR now available on MA/CR
