### ISSUE TITLE
Allow a template to be applied when work item is updated via email

### ISSUE THREAD

**Issue by kenmcmi** [AdhocAdam/smletsexchangeconnector#91]
This is to mimic the stock exchange connector ability.

In the stock exchange connector in the 'Routing and Schedule' section there is an option to select a different template when an incident is updated via the connector.

We are using this today to changes the incidents back to Active (from pending) status when we get a response back.

This would be great to have in the smletsexchangeconnector!!

thank you

**Comment by AdhocAdam** [comment]
You've actually raised a really interesting tangential feature here....

When I originally started putting this thing together, the connector didn't have the "update template" a part of it because my thinking was "I'll only ever update properties. A whole template is unnecessary and if anything, you can make the 'classic' mistake of picking a template with a Support Group and updates always causing a reset of the Support Group." That said, I wanted to even avoid the possibility of that occurring for those coming on board with this. BUT, what you've presented here is an incredibly valid use case. Someone responds to an Incident and you want to apply a template that flips it back to Active. I am **100% on board with this**.

The "tangential" part of the request is this - in a very recent version of the connector how/when the Action Log gets updated was broken out into Affected User actions, Analyst actions, and everyone else's actions. I'm not saying no to the "update template" idea, but what about a $true/$false variable that flip Work Item's to X Status when the Affected User comments? When the Assigned To comments? Basically, introduce a feature that globally and optionally controls the Status when someone replies back. I'm suggesting this because it would introduce _more_ flexibility and control over what the stock connector does which is essentially "any update happens apply a template." But here it would be based on _who_ updated it.

I could honestly be swayed either way as both have their potential advantages/disadvantages. Thoughts?

**Comment by AdhocAdam** [comment]
Also - if you're looking to meet this need _today_ as of this post and v1.4.5 of the connector all you'd have to do is add a...

```powershell
Set-SCSMObject -SMObject $workItem -PropertyHashtable @{"Status" = "IncidentStatusEnum.Active$"}
```

On line 1043 right before the switch statment. This would ensure the Incident gets flipped to Active before any Affected User, Assigned to, or other user action takes place.

**Comment by kenmcmi** [comment]
I agree on not needing to use a template. I had to be extra careful that I wasn’t changing any other values so an update wouldn’t break a support group, classification etc..

We use the Cireson Portal and when we use the ‘Send Email’ function we set the status to Pending. This lets anyone looking inside of the portal know we are waiting on a response back for that particular incident. The template wasn’t the most ideal solution but it got the job done.

I think having a true/false based off Affected/Assigned and/or Related to users, would be great and at the end day just adds more options for the customer to select from.

**Comment by kenmcmi** [comment]
Thanks Adam

I’ll try this out! I was trying to rig something up but wasn’t sure about line placement!

**Comment by AdhocAdam** [comment]
> @kenmcmi said: I think having a true/false based off Affected/Assigned and/or Related to users, would be great and at the end day just adds more options for the customer to select from.

You've raised another interesting feature and gap in the stock connector that we should be able to address. When Related Users leave comment on Work Items, they are treated as Null End User Comments. Which means things like the Cireson Notify Analyst can't fire a notification to the Assigned To user. I've raised it over here #92

**Comment by AdhocAdam** [comment]
The **[AdhocAdam-ChangeStatusOnReply](https://github.com/AdhocAdam/smletsexchangeconnector/tree/AdhocAdam-ChangeStatusOnReply)** branch features the first pass of this functionality scheduled to see its way into [v1.4.6](https://github.com/AdhocAdam/smletsexchangeconnector/milestone/3) of the connector.

**Comment by AdhocAdam** [comment]
Committed into v1.4.6 branch due to release before the year is over.
